### ISSUE TITLE
Fix description of the project

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/prop-types-extra#2]
Some bonus PropTyes => ... PropTypes
<img width="442" alt="1" src="https://user-images.githubusercontent.com/847572/29005669-cc27efd4-7ae8-11e7-8c7e-d83edee02437.png">

**Comment by taion** [comment]
Fixed. Don't you have write access though?

**Comment by AlexKVal** [comment]
I wasn't able to figure it out :)

**Comment by AlexKVal** [comment]
Yeah.. I have no write access for those things @taion :)
<img width="1117" alt="1" src="https://user-images.githubusercontent.com/847572/29073174-4be798da-7c53-11e7-99ff-4cc6a879d8eb.png">
<img width="1113" alt="2" src="https://user-images.githubusercontent.com/847572/29073177-4ef60c0a-7c53-11e7-977b-db5198224ce5.png">

**Comment by jquense** [comment]
oops fixed!

**Comment by AlexKVal** [comment]
<img width="1109" alt="3" src="https://user-images.githubusercontent.com/847572/29073942-363537d8-7c56-11e7-9d5b-ad62a6de6275.png">
@jquense if you mean the write access, then no, it is not :)
but I wouldn't bother about it :)
it is more than enough for me, that you guys have it 👍
